"""`ch init` — make clihub usable: create its directories and put `ch` on PATH.

This is the one command you run by full path, because the whole point of it is that
`ch` is not yet reachable by name. Everything it does is idempotent.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from .. import completion, config
from ..config import load as load_settings
from ..errors import BuiltinError
from ..paths import Paths

# What `ch --help` prints for this command. Separate from __doc__, which is
# about the module: different readers, different words.
SUMMARY = "create the directories, put ch on PATH"
ARGS = ""

DEFAULT_LINK_DIR = Path("~/.local/bin")


def run(argv: list[str], paths: Paths) -> int:
    parser = argparse.ArgumentParser(prog="ch init")
    parser.add_argument("--link-dir", default=str(DEFAULT_LINK_DIR))
    parser.add_argument("--no-link", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument(
        "--completions", action=argparse.BooleanOptionalAction, default=None
    )
    args = parser.parse_args(argv[2:])

    for directory in (paths.root, paths.log_root):
        directory.mkdir(parents=True, exist_ok=True)
    wrote_config = _write_commented_config(paths)
    print(f"home       {paths.root}")
    print(f"registry   {paths.registry_file.name}")
    print(f"config     {paths.config_file.name}"
          f"{'  (written; every key commented out)' if wrote_config else '  (kept yours)'}")
    print(f"log        {paths.log_root.name}/       safe to delete")

    _install_completions(paths, choice=args.completions)

    if args.no_link:
        return 0

    source = _console_script()
    if source is None:
        sys.stderr.write(
            "could not locate the installed `ch` script; skipping the symlink.\n"
            "  install with: pip install -e . ; then re-run ch init\n"
        )
        return 0

    link_dir = Path(args.link_dir).expanduser()
    link_dir.mkdir(parents=True, exist_ok=True)
    link = link_dir / "ch"
    _link(source, link, force=args.force)

    print(f"command    {link} -> {source}")
    if not _on_path(link_dir):
        sys.stderr.write(
            f"\n{link_dir} is not on your PATH. Add it, or pick a directory that is:\n"
            f"  export PATH=\"{link_dir}:$PATH\"\n"
        )
    return 0


def _write_commented_config(paths: Paths) -> bool:
    """Write config.toml as the shipped defaults with every key commented out.

    Generated from defaults.toml rather than copied, so the two cannot drift and a
    key added later shows up here the next time init runs. Commented rather than
    live on purpose: a user file holding real values would shadow every future
    change to a default, so raising a timeout in a release would silently not
    reach anyone who had ever run init.
    """
    if paths.config_file.exists():
        return False
    body = [
        "# clihub settings. Uncomment a line to override it; the value shown is",
        "# what clihub uses when you do not. Generated by `ch init` from the",
        "# defaults shipped in the package -- editing those is not the way.",
        "",
    ]
    lines = config.defaults_text().splitlines()
    # Drop the shipped file's own header: this file has one already, and two
    # headers explaining the same thing differently is how one goes stale.
    while lines and not lines[0].startswith("["):
        lines.pop(0)
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("["):
            body.append(line)
        else:
            body.append(f"# {line}")
    paths.config_file.parent.mkdir(parents=True, exist_ok=True)
    paths.config_file.write_text("\n".join(body).rstrip() + "\n", encoding="utf-8")
    return True


def _install_completions(paths: Paths, *, choice: bool | None) -> None:
    """Off unless asked: init should not edit a shell config on its own initiative.

    `--completions`/`--no-completions` override the config for one run.
    """
    if choice is False:
        return
    if choice is None and not load_settings(paths.config_file).completions_auto_enabled:
        return
    from .tools import install_completion

    install_completion(paths, completion.detect_shell())


def _console_script() -> Path | None:
    """The `ch` pip installed, which sits next to the interpreter running us.

    Deliberately NOT resolved: a venv's bin/python is a symlink back to the base
    interpreter, so resolving it lands in the Homebrew Cellar and leaves the venv
    entirely — where no `ch` exists. The opposite of dispatch, which must resolve to
    find a tool's real path.
    """
    here = Path(sys.executable).parent
    for directory in (_outlives_upgrades(here), here):
        script = directory / "ch"
        if script.is_file():
            return script
    return None


def _outlives_upgrades(bin_dir: Path) -> Path:
    """The same directory named so that a Homebrew upgrade cannot invalidate it.

    Homebrew installs a formula under `Cellar/<formula>/<version>` and points
    `opt/<formula>` at whichever version is current, deleting the tree it
    replaced. A link into Cellar dangles one upgrade later; the opt path does
    not. Any other layout is returned unchanged.
    """
    parts = bin_dir.parts
    if "Cellar" not in parts:
        return bin_dir
    cellar = parts.index("Cellar")
    if len(parts) <= cellar + 2:
        return bin_dir
    return Path(*parts[:cellar], "opt", parts[cellar + 1], *parts[cellar + 3:])


def _link(source: Path, link: Path, *, force: bool) -> None:
    if link.is_symlink() or link.exists():
        # Refuse silently replacing something the user put there — same rule as
        # `tools add`: an existing entry is only replaced when asked explicitly.
        if link.is_symlink() and link.resolve() == source.resolve():
            return
        if not force:
            raise BuiltinError(
                f"{link} already exists and does not point at {source}. "
                "Re-run with --force to replace it."
            )
        link.unlink()
    link.symlink_to(source)


def _on_path(directory: Path) -> bool:
    entries = os.environ.get("PATH", "").split(os.pathsep)
    resolved = directory.expanduser().resolve()
    for entry in entries:
        if not entry:
            continue
        try:
            if Path(entry).expanduser().resolve() == resolved:
                return True
        except OSError:
            continue
    return False
